#!/usr/bin/env python3
"""
Generate the regional screw piling pages (services/screw-piling-<city>.html).

Part of the Sutera service x suburb coverage program. TPE deliberately does NOT get a
metro suburb spine: piling is bought at metro/state level by builders and engineers, and
every term this site ranks for is "<service> melbourne" or "<service> victoria", not a
suburb. See CRM/operations/service-suburb-coverage.md for the 3-layer model. This script
builds Layer 2: the regional cities TPE genuinely travels to, where "we work all over
Victoria no matter the distance" is a competitive moat rather than a keyword play.

Content rules enforced here (from the site CLAUDE.md, do not relax without James):
  - No speed / turnaround / response-time claims of any kind, anywhere.
  - No "Tier 1". "Government experience" is the trust anchor instead.
  - No contact form. Phone + email CTAs only.
  - No em dashes or en dashes.
  - NO FABRICATED PROJECT LOCATIONS. These pages claim a SERVICE AREA and describe real,
    publicly known ground conditions for each region. They never state or imply that a
    job was done in a named town. When Tom supplies the real job list, add proof then.

Header nav and footer are sliced live out of services/screw-piling.html so the
"nav + footer identical on every page" rule cannot drift. Re-running is safe and
idempotent: it overwrites the generated pages, re-writes the Areas We Service block on
the parent page between its markers, and de-duplicates sitemap entries.

Usage:  python3 .build/gen_city_pages.py
"""

import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PARENT = os.path.join(ROOT, "services", "screw-piling.html")
BASE = "https://www.totalpilingandexcavations.com.au"
TODAY = "2026-08-14"

PHONE_ROB = "0419 008 549"
PHONE_TOM = "0448 725 807"

# Markers for the idempotent Areas We Service block on the parent page.
AREAS_START = "<!-- AREAS_WE_SERVICE:START (generated by .build/gen_city_pages.py) -->"
AREAS_END = "<!-- AREAS_WE_SERVICE:END -->"


CITIES = [
    {
        "slug": "echuca",
        "blurb": "Murray floodplain ground, riverfront and rural builds, and the Campaspe corridor across to Moama.",
        "name": "Echuca",
        "region": "Echuca &amp; the Murray",
        "geo": "Echuca",
        "eyebrow": "Northern Victoria",
        "h1": "Screw Piling<br>Echuca &amp; the Murray.",
        "lead": "Certified screw pile foundations across Echuca, Moama and the Campaspe corridor. "
                "Melbourne and Echuca bases, AS2159 engineered, 100% Australian-made piles, and full "
                "certification with every install.",
        "meta_desc": "Screw piling in Echuca, Moama and northern Victoria. Certified AS2159 screw pile "
                     "foundations for riverfront, rural and town builds. Australian-made piles, certificate "
                     "on completion.",
        "keywords": "screw piling Echuca, screw piles Echuca, screw piling Moama, helical piles northern Victoria, "
                    "foundation contractor Echuca, screw pile installation Campaspe",
        "photo": "screw-piling-rural-aerial.jpg",
        "photo_w": 1440, "photo_h": 817,
        "photo_alt": "Aerial view of a completed screw pile grid laid out across a rural Victorian pad",
        "ground_h2": "River country ground, engineered properly.",
        "ground": [
            "Echuca sits on the Murray floodplain, and the ground shows it. The profile through town and out "
            "across the surrounding irrigation country is typically alluvial: sandy loams and silts laid down by "
            "the river, sitting over deeper clay, with a water table that runs high close to the river and rises "
            "further through wet years. It is soft, variable, water-affected ground, and it is not forgiving of a "
            "foundation that was designed on assumption rather than on a soil report.",
            "That profile is exactly where screw piles earn their place. There is no excavation pit to dig and "
            "watch fill with water, no concrete sitting in saturated ground, and almost no spoil to cart away. "
            "The pile is rotated down through the soft upper material until it reaches the load-bearing depth "
            "and design torque your engineer has specified, and the torque reading on each pile tells us what it "
            "is actually bearing on rather than what a drawing predicted.",
            "Total Piling works Echuca and the surrounding district off our northern Victorian base, with the "
            "Melbourne operation behind it for machinery and pile stock. Riverfront residential, rural and "
            "acreage builds, town extensions, sheds and agricultural infrastructure all get the same certified "
            "AS2159 install and the same documentation at handover.",
        ],
        "soil_sub": "Alluvial river profiles, sandy loam over clay, and high water table sites near the Murray.",
        "usecases": [
            ("Riverfront residential", "Homes, extensions and decks on Murray frontage blocks where the water "
                                       "table is high and the upper profile is soft."),
            ("Rural &amp; acreage", "Sheds, machinery bays, transportable and modular homes, and outbuildings "
                                    "across the surrounding farming country."),
            ("Town builds &amp; extensions", "New builds, second-storey additions and granny flats through Echuca "
                                             "and Moama, including tight side-access blocks."),
            ("Agricultural &amp; commercial", "Irrigation infrastructure, storage and processing pads, and "
                                              "commercial footings engineered to the soil report."),
        ],
        "area_h2": "Echuca and surrounds",
        "area_sub": "One crew, the whole northern corridor. We bring the machine, the pile stock and the "
                    "certification with us.",
        "area_items": [
            ("Echuca &amp; Moama", "Both sides", "The twin towns either side of the Murray. Moama is in NSW, and "
                                                  "we work both banks."),
            ("Campaspe corridor", "Town to town", "Rochester, Kyabram, Tongala, Lockington and Elmore, plus the "
                                                   "farming country in between."),
            ("Wider Murray", "On request", "Out to Deniliquin, Cohuna and Kerang where the job scope justifies "
                                            "the travel. Send the site details."),
        ],
        "faqs": [
            ("Do you cover Moama and the NSW side of the river?",
             "Yes. Moama sits directly across the Murray from Echuca and we work both banks as one service area. "
             "Interstate civil and government work is available more broadly on request when the job scope "
             "justifies the travel. Send us the site address with the plans and we will quote it."),
            ("Can screw piles handle the high water table around Echuca?",
             "Yes, and this is one of the strongest arguments for them here. A screw pile is driven mechanically "
             "rather than poured, so there is no open excavation filling with water and no concrete curing in a "
             "saturated profile. The pile passes through the soft, wet upper material and anchors in competent "
             "load-bearing soil below, with install torque recorded against the engineer's design."),
            ("Which towns around Echuca do you travel to?",
             "Rochester, Kyabram, Tongala, Lockington and Elmore through the Campaspe corridor, and out to "
             "Deniliquin, Cohuna and Kerang where the job warrants it. We bring the machine, the pile stock and "
             "the certification with us, so a job out of town is run to the same standard as one in town."),
            ("Do you work on flood-affected ground?",
             "Foundation design on the northern plains has to account for ground that can sit saturated for "
             "extended periods, and that is a soil report and engineering question on every individual site. "
             "Send through the soil report and the engineer's design with your plans and we will quote the pile "
             "sizing and depth against them."),
        ],
    },
    {
        "slug": "geelong",
        "blurb": "Reactive basalt clay across the plains and sand over clay toward the Bellarine coast.",
        "name": "Geelong",
        "region": "Geelong &amp; the Bellarine",
        "geo": "Geelong",
        "eyebrow": "South west Victoria",
        "h1": "Screw Piling<br>Geelong &amp; the Bellarine.",
        "lead": "Certified screw pile foundations across Geelong, the growth corridor and the Bellarine coast. "
                "AS2159 engineered, 100% Australian-made piles, and full certification with every install.",
        "meta_desc": "Screw piling in Geelong and the Bellarine. Certified AS2159 screw pile foundations for "
                     "reactive clay and coastal sand sites. Australian-made piles, certificate on completion.",
        "keywords": "screw piling Geelong, screw piles Geelong, helical piles Geelong, screw piling Bellarine, "
                    "foundation contractor Geelong, screw pile installation Armstrong Creek",
        "photo": "screw-piling-waterfront-drilling.jpg",
        "photo_w": 1440, "photo_h": 1439,
        "photo_alt": "Total Piling branded excavator driving screw piles on a waterfront residential site",
        "ground_h2": "Two very different ground profiles.",
        "ground": [
            "Geelong is really two foundation problems in one region. Across the northern and western plains, "
            "through Corio, Lara, Norlane and out into the Armstrong Creek growth corridor, the ground is "
            "basalt-derived reactive clay. It swells when it takes water and shrinks back when it dries, and that "
            "seasonal movement is the single most common cause of foundation trouble in this part of the state.",
            "Head toward the coast and the problem inverts. Through the Bellarine and the surf coast side the "
            "profile turns to sand over clay with a water table that can sit close to the surface, which is loose "
            "and low-bearing near the top and needs the load carried down to something competent underneath.",
            "Screw piles answer both. In reactive clay the pile passes straight through the active zone and "
            "anchors below it, so the structure is not riding the seasonal movement. In coastal sand the pile is "
            "taken down to the bearing layer with the install torque recorded on every pile against the "
            "engineer's design. No concrete, no excavation pit, and minimal disruption to established "
            "landscaping on the infill blocks.",
        ],
        "soil_sub": "Reactive basalt clay across the plains, sand over clay and high water table toward the coast.",
        "usecases": [
            ("Growth corridor residential", "New homes and slab pads through Armstrong Creek, Charlemont, Lara "
                                            "and the surrounding estates, engineered to the soil report."),
            ("Coastal &amp; waterfront", "Bellarine and bayside builds, decks and pool surrounds on sandy "
                                          "profiles and high water table sites."),
            ("Extensions &amp; decks", "Additions, second-storey adds, granny flats and large decks on reactive "
                                        "clay blocks. Tight access capable through side gates."),
            ("Commercial &amp; multi-unit", "Multi-house developments, modular commercial buildings and retail "
                                             "pads, delivered as a programmed pile grid."),
        ],
        "area_h2": "Geelong and surrounds",
        "area_sub": "Covered off the Melbourne base, with the machinery and pile stock to match the site.",
        "area_items": [
            ("Greater Geelong", "All suburbs", "Corio, Lara, Norlane, Belmont, Highton, Waurn Ponds and the "
                                                "Armstrong Creek corridor."),
            ("The Bellarine", "Coast to coast", "Ocean Grove, Barwon Heads, Drysdale, Portarlington and Queenscliff, "
                                                 "on coastal sand and high water table profiles."),
            ("Surf Coast", "On request", "Torquay, Jan Juc and along the coast where the job scope justifies the "
                                          "travel. Send the site details."),
        ],
        "faqs": [
            ("Are screw piles suitable for Geelong's reactive clay?",
             "Yes, and reactive clay is one of the profiles they suit best. The clay through the Geelong plains "
             "swells and shrinks with moisture, and that movement is concentrated in the upper active zone. A "
             "screw pile passes through that zone entirely and anchors in stable load-bearing material below, so "
             "the structure sits on ground that is not moving seasonally."),
            ("What about sandy coastal blocks on the Bellarine?",
             "Sand over clay with a high water table is a normal screw pile situation. The pile is taken down "
             "past the loose surface material to the bearing layer specified by the engineer, and because it is "
             "driven rather than poured, there is no open excavation filling with water and no concrete curing "
             "in a wet profile."),
            ("Do you cover Torquay, Ocean Grove and the surf coast?",
             "Yes. Geelong, the Bellarine and the surf coast are all within the service area, and we bring the "
             "machine and pile stock with us. Send the plans, engineering and soil report with the site address "
             "and we will quote it."),
            ("Do you charge more because you are based in Melbourne?",
             "Send the job details through and the quote will be itemised: pile counts, sizes, depth, connection "
             "detail and certification, all on the page and all priced. We work across Victoria as a matter of "
             "course, so regional work is normal for us rather than an exception."),
        ],
    },
    {
        "slug": "bendigo",
        "blurb": "Variable goldfields ground, sloping blocks and heritage sites across central Victoria.",
        "name": "Bendigo",
        "region": "Bendigo &amp; the goldfields",
        "geo": "Bendigo",
        "eyebrow": "Central Victoria",
        "h1": "Screw Piling<br>Bendigo &amp; the goldfields.",
        "lead": "Certified screw pile foundations across Bendigo and central Victoria, including the variable "
                "goldfields ground the region is known for. AS2159 engineered, 100% Australian-made piles, full "
                "certification with every install.",
        "meta_desc": "Screw piling in Bendigo and central Victoria. Certified AS2159 screw pile foundations for "
                     "goldfields ground, sloping blocks and heritage sites. Australian-made piles, certificate on "
                     "completion.",
        "keywords": "screw piling Bendigo, screw piles Bendigo, helical piles Bendigo, foundation contractor Bendigo, "
                    "screw pile installation central Victoria, goldfields foundations",
        "photo": "screw-piling-rural-grid.jpg",
        "photo_w": 1440, "photo_h": 1920,
        "photo_alt": "Engineered grid of screw piles installed across a Victorian site",
        "ground_h2": "Goldfields ground changes across a block.",
        "ground": [
            "Bendigo is goldfields country, and that history is still in the ground. Weathered rock can sit close "
            "to the surface in one part of a site and drop away in another, and the older parts of town carry a "
            "long legacy of shallow workings, shafts and backfilled ground. It is genuinely variable material, "
            "and a foundation approach that assumes a uniform profile across a block is making an assumption the "
            "ground has not agreed to.",
            "Screw piling handles that variability better than most methods, because the install itself is a "
            "measurement. Every pile is driven to the design torque specified by the engineer, and the torque "
            "reading is a live read on what that individual pile is bearing on. Where the profile changes across "
            "a site, the piles tell you, and the engineer adjusts depth or sizing against real numbers rather "
            "than a projection.",
            "Add the sloping blocks through Strathdale, Junortoun and Kennington, and the heritage housing stock "
            "through the centre of town, and you have a region where minimal excavation matters. No concrete "
            "pour, no spoil to truck out, and installs that can be run around established gardens and existing "
            "structures.",
        ],
        "soil_sub": "Variable goldfields profiles, weathered rock at changing depths, and historic worked ground.",
        "usecases": [
            ("Sloping blocks", "Level, engineered pile grids on the fall through Strathdale, Junortoun, "
                                "Kennington and the surrounding hills."),
            ("Heritage &amp; extensions", "Additions and second-storey adds around established homes and mature "
                                           "gardens, with minimal excavation and no spoil."),
            ("New residential estates", "Slab pads and footings across the growth areas out toward Huntly, Marong "
                                         "and Strathfieldsaye."),
            ("Commercial &amp; civil", "Retail pads, modular commercial buildings, signage and utility "
                                        "foundations, engineered to spec and audit ready."),
        ],
        "area_h2": "Bendigo and surrounds",
        "area_sub": "Central Victorian coverage with the machinery and pile stock brought to site.",
        "area_items": [
            ("Greater Bendigo", "All suburbs", "Strathdale, Kennington, Junortoun, Eaglehawk, Epsom, Huntly, "
                                                "Marong and Strathfieldsaye."),
            ("Central goldfields", "Town to town", "Castlemaine, Maldon, Heathcote and Elmore, on the same "
                                                    "variable worked ground."),
            ("Wider region", "On request", "Further into central and northern Victoria where the job scope "
                                            "justifies the travel. Send the site details."),
        ],
        "faqs": [
            ("How do screw piles cope with variable goldfields ground?",
             "Better than most options, because the install doubles as a measurement. Each pile is driven to the "
             "design torque set by your engineer, and that torque reading shows what the individual pile is "
             "bearing on. Where the profile changes across a site, which is common through Bendigo, the piles "
             "surface it during the install rather than after the build."),
            ("What happens if a pile hits rock shallow?",
             "It gets referred back to the engineering. Shallow refusal is a normal outcome in goldfields "
             "country, and the engineer determines whether that depth satisfies the design or whether the pile "
             "position or sizing needs to change. It is resolved against the soil report and the design, not "
             "improvised on site."),
            ("Do you cover Castlemaine, Heathcote and the smaller towns?",
             "Yes. Castlemaine, Maldon, Heathcote and Elmore all sit within the central Victorian service area, "
             "and we bring the machine, pile stock and certification with us. Send the site address through with "
             "the plans and we will quote it."),
            ("Are the installs certified?",
             "Every install is engineered to AS2159, the Australian Standard for piling design and installation. "
             "We record install torque on each pile against the engineer's design, perform load testing where it "
             "is specified, and hand over a certificate of compliance with the build documentation."),
        ],
    },
    {
        "slug": "ballarat",
        "blurb": "Heavy clay that stays wet through winter, plus historic worked ground in the older suburbs.",
        "name": "Ballarat",
        "region": "Ballarat &amp; the Central Highlands",
        "geo": "Ballarat",
        "eyebrow": "Western Victoria",
        "h1": "Screw Piling<br>Ballarat &amp; the Highlands.",
        "lead": "Certified screw pile foundations across Ballarat and the Central Highlands, on the heavy clay "
                "and worked ground the region sits on. AS2159 engineered, 100% Australian-made piles, full "
                "certification with every install.",
        "meta_desc": "Screw piling in Ballarat and the Central Highlands. Certified AS2159 screw pile foundations "
                     "for heavy clay, wet ground and goldfields sites. Australian-made piles, certificate on "
                     "completion.",
        "keywords": "screw piling Ballarat, screw piles Ballarat, helical piles Ballarat, foundation contractor "
                    "Ballarat, screw pile installation Central Highlands, Ballarat foundations",
        "photo": "job-rural-pile-grid.jpg",
        "photo_w": 1050, "photo_h": 1400,
        "photo_alt": "Engineered grid of screw piles installed across a rural Victorian pad",
        "ground_h2": "Heavy clay, wet ground, worked history.",
        "ground": [
            "Ballarat gives a foundation three things to deal with at once. The ground is largely heavy clay over "
            "weathered bedrock and basalt, the region takes more rainfall and colder winters than most of the "
            "state so that clay sits saturated for long stretches of the year, and the older suburbs carry the "
            "same goldfields legacy of shallow historic workings and backfilled ground that runs through this "
            "part of Victoria.",
            "Wet, heavy, reactive clay is difficult ground for anything that relies on an open excavation or a "
            "concrete pour. A screw pile avoids both. It is rotated down through the reactive upper zone and "
            "anchored in stable material below, with no pit to dig, no water sitting in an open hole, and almost "
            "no spoil to cart off a site that is already soft underfoot.",
            "That makes it a practical option through a Ballarat winter as well as a structural one. The install "
            "leaves established gardens, paths and driveways largely intact on the older infill blocks, and every "
            "pile is driven to the design torque and certified to AS2159 on completion.",
        ],
        "soil_sub": "Heavy clay over weathered bedrock, saturated for long stretches, with historic worked ground.",
        "usecases": [
            ("New residential", "Slab pads and footings through Lucas, Alfredton, Winter Valley and the western "
                                 "growth estates, engineered to the soil report."),
            ("Extensions &amp; decks", "Additions, granny flats and large decks around established homes and "
                                        "mature gardens, with minimal excavation."),
            ("Wet &amp; sloping sites", "Blocks that stay soft through winter or fall away across the site, where "
                                         "an open excavation is impractical."),
            ("Commercial &amp; civil", "Retail and modular commercial pads, signage, utility and gantry "
                                        "foundations, engineered to spec and audit ready."),
        ],
        "area_h2": "Ballarat and surrounds",
        "area_sub": "Central Highlands coverage, with the machine and pile stock brought to site.",
        "area_items": [
            ("Greater Ballarat", "All suburbs", "Ballarat East and Central, Alfredton, Lucas, Winter Valley, "
                                                 "Sebastopol, Wendouree and Buninyong."),
            ("Central Highlands", "Town to town", "Creswick, Clunes, Daylesford, Bacchus Marsh and Ballan across "
                                                   "the surrounding highlands."),
            ("Western district", "On request", "Ararat, Beaufort and further west where the job scope justifies "
                                                "the travel. Send the site details."),
        ],
        "faqs": [
            ("Can screw piles go in through a Ballarat winter?",
             "The method suits wet ground better than the alternatives, because there is no open excavation to "
             "fill with water and no concrete curing in a saturated profile. Site access and the engineer's "
             "design still govern what happens on any given job, so send the plans and soil report through and "
             "we will quote it against the actual conditions."),
            ("Does the heavy clay around Ballarat cause foundation movement?",
             "Reactive clay moves as it takes on and gives up moisture, and that movement is concentrated in the "
             "upper active zone. A screw pile is driven through that zone and anchored in stable load-bearing "
             "material underneath, so the structure is supported below the layer that is doing the moving."),
            ("Do you cover Creswick, Daylesford and Bacchus Marsh?",
             "Yes. The Central Highlands towns sit within the service area, along with Clunes, Ballan and out "
             "toward Ararat where the job warrants it. We bring the machine, the pile stock and the "
             "certification with us."),
            ("What do you need to quote a Ballarat job?",
             "Plans, the engineering, and a soil report if you have one. That gives us pile counts, sizes, depth "
             "and connection detail to price properly, and the quote comes back itemised rather than as an "
             "estimate. Email them to sales@totalpiling.com.au or call Rob or Tom."),
        ],
    },
    {
        "slug": "shepparton",
        "blurb": "Deep alluvial Goulburn Valley soils, agricultural pads and food processing footings.",
        "name": "Shepparton",
        "region": "Shepparton &amp; the Goulburn Valley",
        "geo": "Shepparton",
        "eyebrow": "Goulburn Valley",
        "h1": "Screw Piling<br>Shepparton &amp; the Valley.",
        "lead": "Certified screw pile foundations across Shepparton and the Goulburn Valley, on deep alluvial "
                "ground where bearing comes from depth. AS2159 engineered, 100% Australian-made piles, full "
                "certification with every install.",
        "meta_desc": "Screw piling in Shepparton and the Goulburn Valley. Certified AS2159 screw pile foundations "
                     "for deep alluvial soils, agricultural and commercial pads. Australian-made piles, certificate "
                     "on completion.",
        "keywords": "screw piling Shepparton, screw piles Shepparton, helical piles Goulburn Valley, foundation "
                    "contractor Shepparton, screw pile installation Mooroopna, agricultural shed foundations",
        "photo": "screw-piling-rural-aerial-completed.jpg",
        "photo_w": 1440, "photo_h": 817,
        "photo_alt": "Aerial view of a completed screw pile grid on a rural Victorian pad",
        "ground_h2": "Deep alluvial ground, bearing from depth.",
        "ground": [
            "The Goulburn Valley is floodplain. The ground through Shepparton, Mooroopna and the surrounding "
            "irrigation district is deep alluvial material laid down by the Goulburn and Broken rivers: silty "
            "clays and loams running well down, with a water table that sits shallow across much of the district "
            "and rises through wet years. There is very little rock near the surface, which means bearing comes "
            "from depth rather than from refusal on something hard.",
            "That is a straightforward brief for screw piling and an awkward one for methods that need a stable "
            "open hole. The pile is rotated down until it reaches the design torque the engineer has specified, "
            "with the torque recorded on every pile, so the load is carried on material that has been measured "
            "rather than assumed. No excavation pit standing open in a shallow water table, no concrete curing in "
            "wet ground, and almost no spoil to move.",
            "The Valley's building mix leans heavily on agriculture and food processing alongside its residential "
            "growth, which means shed pads, storage and processing footings and civil work sit next to houses and "
            "extensions on the same job list. All of it gets the same AS2159 engineered install and the same "
            "documentation at handover.",
        ],
        "soil_sub": "Deep alluvial silts and clays with a shallow water table. Bearing comes from depth.",
        "usecases": [
            ("Agricultural &amp; shed pads", "Machinery sheds, storage, hay and equipment bays across the "
                                              "irrigation district, set out as an engineered pile grid."),
            ("Food processing &amp; commercial", "Processing and cool store footings, plant pads and commercial "
                                                  "buildings engineered to spec and audit ready."),
            ("Residential &amp; extensions", "New homes, additions, granny flats and decks through Shepparton, "
                                              "Mooroopna and Kialla."),
            ("Civil &amp; infrastructure", "Irrigation infrastructure, utilities, signage and gantry "
                                            "foundations across the Valley."),
        ],
        "area_h2": "Shepparton and surrounds",
        "area_sub": "Goulburn Valley coverage, with machinery and pile stock brought to site.",
        "area_items": [
            ("Greater Shepparton", "All suburbs", "Shepparton, Mooroopna, Kialla, Tatura and the surrounding "
                                                   "irrigation country."),
            ("Goulburn Valley", "Town to town", "Numurkah, Nathalia, Cobram, Euroa and Benalla across the "
                                                 "wider Valley."),
            ("Wider north east", "On request", "Further into north eastern Victoria where the job scope "
                                                "justifies the travel. Send the site details."),
        ],
        "faqs": [
            ("How deep do screw piles go in Goulburn Valley soil?",
             "Depth is set by the engineer against the soil report, not by a rule of thumb. Because the Valley "
             "profile is deep alluvial material with little near-surface rock, bearing generally comes from depth "
             "rather than from refusal, and the pile is driven until it reaches the design torque specified for "
             "that site."),
            ("Is the shallow water table a problem?",
             "It is a problem for methods that need a stable open excavation, and much less of one for screw "
             "piles. Nothing is dug out and nothing is poured, so there is no hole standing open in wet ground "
             "and no concrete curing in a saturated profile. The pile is driven and certified on completion."),
            ("Do you do agricultural shed and storage pads?",
             "Yes. Machinery sheds, storage and hay bays, processing and cool store footings and general "
             "commercial pads are all standard work, delivered as a programmed pile grid set out to the "
             "building footprint and engineered to AS2159."),
            ("Which Valley towns do you cover?",
             "Shepparton, Mooroopna, Kialla and Tatura through the centre, and Numurkah, Nathalia, Cobram, Euroa "
             "and Benalla across the wider Valley. We bring the machine, the pile stock and the certification "
             "with us."),
        ],
    },
    {
        "slug": "traralgon",
        "blurb": "Latrobe Valley alluvial flats and made ground, residential through to industrial and plant.",
        "name": "Traralgon",
        "region": "Traralgon &amp; the Latrobe Valley",
        "geo": "Traralgon",
        "eyebrow": "Gippsland",
        "h1": "Screw Piling<br>Traralgon &amp; Gippsland.",
        "lead": "Certified screw pile foundations across Traralgon and the Latrobe Valley, on the mixed natural "
                "and made ground the Valley is built on. AS2159 engineered, 100% Australian-made piles, full "
                "certification with every install.",
        "meta_desc": "Screw piling in Traralgon and the Latrobe Valley. Certified AS2159 screw pile foundations "
                     "for alluvial flats, fill and industrial sites across Gippsland. Australian-made piles, "
                     "certificate on completion.",
        "keywords": "screw piling Traralgon, screw piles Latrobe Valley, helical piles Gippsland, foundation "
                    "contractor Traralgon, screw pile installation Morwell, Gippsland foundations",
        "photo": "screw-piling-grid-aerial.jpg",
        "photo_w": 1440, "photo_h": 817,
        "photo_alt": "Aerial view of an engineered screw pile grid set out across a Victorian site",
        "ground_h2": "Natural ground and made ground, side by side.",
        "ground": [
            "The Latrobe Valley is a mix. There are alluvial flats running along the Latrobe River with soft, "
            "water-affected profiles, there is natural clay and sand through the surrounding country, and after "
            "a long industrial history there are also areas of fill and made ground where what is underneath is "
            "not what the surface suggests. Ground conditions can differ substantially between two sites a few "
            "streets apart, which puts a lot of weight on the soil report.",
            "Screw piling suits that uncertainty because the install verifies itself. Each pile is driven to the "
            "design torque set by the engineer and that reading reflects what the individual pile is actually "
            "bearing on. Where a site turns out to be more variable than expected, the piles surface it during "
            "installation and the engineering is adjusted against real numbers.",
            "The Valley's job mix runs from residential builds and extensions through to industrial and plant "
            "work, and screw piles cover both ends of it. No concrete pour, no excavation pit, minimal spoil, "
            "and an AS2159 certified install with full documentation at handover.",
        ],
        "soil_sub": "Alluvial river flats, natural clay and sand, and areas of fill from a long industrial history.",
        "usecases": [
            ("Residential &amp; extensions", "New homes, additions, granny flats and decks through Traralgon, "
                                              "Morwell, Moe and Churchill."),
            ("Industrial &amp; plant", "Plant pads, equipment footings and industrial building foundations, "
                                        "engineered to spec and audit ready."),
            ("Rural &amp; acreage", "Sheds, machinery bays and transportable homes across the surrounding "
                                     "Gippsland farming country."),
            ("Civil &amp; infrastructure", "Utilities, signage, gantry and road-adjacent foundations engineered "
                                            "to the design."),
        ],
        "area_h2": "Traralgon and surrounds",
        "area_sub": "Gippsland coverage, with the machine and pile stock brought to site.",
        "area_items": [
            ("Latrobe Valley", "Valley wide", "Traralgon, Morwell, Moe, Newborough and Churchill across the "
                                               "Valley floor."),
            ("Central Gippsland", "Town to town", "Warragul, Drouin, Sale and Maffra through the surrounding "
                                                   "district."),
            ("Wider Gippsland", "On request", "Further east and into South Gippsland where the job scope "
                                               "justifies the travel. Send the site details."),
        ],
        "faqs": [
            ("How do you deal with fill and made ground in the Valley?",
             "By measuring it. Each pile is driven to the design torque specified by the engineer, and that "
             "torque reading shows what the pile is bearing on rather than what was expected. Fill is passed "
             "through to competent material below, and where a site proves more variable than the report "
             "suggested, the engineering is adjusted against the actual readings."),
            ("Do you do industrial and plant foundations?",
             "Yes. Plant pads, equipment footings and industrial building foundations are standard work "
             "alongside the residential side, engineered to AS2159 with install torque recorded on every pile "
             "and full documentation handed over for audit."),
            ("Which Gippsland towns do you cover?",
             "Traralgon, Morwell, Moe, Newborough and Churchill through the Valley, and Warragul, Drouin, Sale "
             "and Maffra across central Gippsland. Further east on request where the job scope justifies the "
             "travel."),
            ("Can you work on soft ground along the Latrobe River flats?",
             "Soft, water-affected alluvial ground is a normal screw pile situation. The pile passes through the "
             "soft upper profile and anchors in load-bearing material below, with no open excavation and no "
             "concrete curing in wet ground. The soil report and the engineer's design set the depth."),
        ],
    },
]


# ---------------------------------------------------------------------------
# Shared chrome, sliced live out of the parent page so nav/footer cannot drift
# ---------------------------------------------------------------------------

def slice_between(src, start, end, label):
    i = src.find(start)
    if i == -1:
        raise SystemExit("Could not find start of %s in the parent page" % label)
    j = src.find(end, i)
    if j == -1:
        raise SystemExit("Could not find end of %s in the parent page" % label)
    return src[i:j + len(end)]


def build_head(city, chrome):
    url = "%s/services/screw-piling-%s.html" % (BASE, city["slug"])
    img = "%s/assets/projects/%s" % (BASE, city["photo"])
    plain = city["name"]
    title = "Screw Piling %s | Total Piling &amp; Excavations" % plain
    og_title = "Screw Piling %s | Total Piling & Excavations" % plain

    ld = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {"@type": "ListItem", "position": 1, "name": "Home", "item": BASE + "/"},
                    {"@type": "ListItem", "position": 2, "name": "Services",
                     "item": BASE + "/services.html"},
                    {"@type": "ListItem", "position": 3, "name": "Screw Piling",
                     "item": BASE + "/services/screw-piling.html"},
                    {"@type": "ListItem", "position": 4, "name": plain, "item": url},
                ],
            },
            {
                "@type": "Service",
                "name": "Screw Piling %s" % plain,
                "serviceType": "Screw Piling",
                "url": url,
                "provider": {
                    "@type": "LocalBusiness",
                    "name": "Total Piling & Excavations",
                    "url": BASE + "/",
                    "telephone": "+61419008549",
                    "address": {"@type": "PostalAddress", "addressRegion": "VIC", "addressCountry": "AU"},
                },
                "areaServed": {"@type": "City", "name": plain, "containedInPlace":
                               {"@type": "State", "name": "Victoria"}},
                "description": re.sub(r"\s+", " ", city["meta_desc"]),
                "offers": {"@type": "Offer", "availability": "https://schema.org/InStock",
                           "areaServed": {"@type": "City", "name": plain}},
            },
            {
                "@type": "FAQPage",
                "mainEntity": [
                    {"@type": "Question", "name": q,
                     "acceptedAnswer": {"@type": "Answer", "text": a}}
                    for q, a in city["faqs"]
                ],
            },
        ],
    }

    return """<!DOCTYPE html>
<html lang="en-AU">
<head>
__GA4__
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>__TITLE__</title>
  <link rel="apple-touch-icon" href="../assets/logo/icon.png">
  <link rel="icon" href="../assets/logo/icon.png">
  <meta name="description" content="__DESC__">
  <meta name="keywords" content="__KEYWORDS__">
  <meta name="robots" content="index, follow">
  <meta name="geo.region" content="AU-VIC">
  <meta name="geo.placename" content="__GEO__">
  <link rel="canonical" href="__URL__">

  <meta property="og:title" content="__OGTITLE__">
  <meta property="og:description" content="__DESC__">
  <meta property="og:type" content="website">
  <meta property="og:locale" content="en_AU">
  <meta property="og:url" content="__URL__">
  <meta property="og:site_name" content="Total Piling &amp; Excavations">
  <meta property="og:image" content="__IMG__">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="__OGTITLE__">
  <meta name="twitter:description" content="__DESC__">
  <meta name="twitter:image" content="__IMG__">

  <script type="application/ld+json">
__LD__
  </script>

__FONTS__
__LEADEV__
</head>
""".replace("__GA4__", chrome["ga4"]) \
   .replace("__FONTS__", chrome["fonts"]) \
   .replace("__LEADEV__", chrome["leadev"]) \
   .replace("__TITLE__", title) \
   .replace("__OGTITLE__", og_title) \
   .replace("__DESC__", re.sub(r"\s+", " ", city["meta_desc"])) \
   .replace("__KEYWORDS__", city["keywords"]) \
   .replace("__GEO__", city["geo"]) \
   .replace("__URL__", url) \
   .replace("__IMG__", img) \
   .replace("__LD__", json.dumps(ld, indent=2, ensure_ascii=False))


def build_body(city, chrome):
    paras = "\n          ".join("<p>%s</p>" % p for p in city["ground"])
    usecases = "\n        ".join(
        '<article class="usecase-card">\n          <h3>%s</h3>\n          <p>%s</p>\n        </article>'
        % (t, d) for t, d in city["usecases"])
    areas = "\n        ".join(
        '<div class="capability-item">\n          <p class="capability-label">%s</p>\n'
        '          <p class="capability-value">%s</p>\n          <p class="capability-sub">%s</p>\n        </div>'
        % (lab, val, sub) for lab, val, sub in city["area_items"])
    faqs = "\n        ".join(
        "<details>\n          <summary>%s</summary>\n          <p>%s</p>\n        </details>"
        % (q, a) for q, a in city["faqs"])

    return """<body>

<a class="skip-link" href="#main">Skip to content</a>

__HEADER__

<main id="main">

  <section class="page-hero" style="--page-hero-bg: url('/assets/core-specialty.jpg');">
    <div class="container page-hero-inner">
      <nav class="breadcrumbs" aria-label="Breadcrumb">
        <ol>
          <li><a href="/">Home</a></li>
          <li><a href="/services.html">Services</a></li>
          <li><a href="/services/screw-piling.html">Screw Piling</a></li>
          <li aria-current="page">__NAME__</li>
        </ol>
      </nav>
      <p class="eyebrow">__EYEBROW__</p>
      <h1>__H1__</h1>
      <p class="page-hero-lead">__LEAD__</p>
      <div class="page-hero-cta">
        <a href="/contact.html" class="btn btn-primary btn-lg">Get a Free Quote</a>
        <a href="tel:0419008549" class="btn btn-ghost btn-lg">Call __PHONE_ROB__</a>
      </div>
    </div>
  </section>

  <section class="content-split">
    <div class="container">
      <div class="content-split-grid">
        <div class="content-split-copy">
          <p class="eyebrow">The ground here</p>
          <h2>__GROUND_H2__</h2>
          __PARAS__
        </div>
        <div class="content-split-media">
          <img width="__PW__" height="__PH__" src="../assets/projects/__PHOTO__" alt="__PALT__" loading="lazy">
        </div>
      </div>
    </div>
  </section>

  <section class="capability-band" aria-label="Screw piling specifications">
    <div class="container">
      <header class="section-head">
        <p class="eyebrow">The specs</p>
        <h2>Engineered to AS2159</h2>
        <p class="section-sub">Australian-made, load-certified, suited to most Victorian soil profiles.</p>
      </header>
      <div class="capability-grid">
        <div class="capability-item">
          <p class="capability-label">Pile sizes</p>
          <p class="capability-value">76 to 114 mm</p>
          <p class="capability-sub">Stocked standard range. Larger sizes upon request.</p>
        </div>
        <div class="capability-item">
          <p class="capability-label">Load capacity</p>
          <p class="capability-value">10,000 to 25,000+ kg</p>
          <p class="capability-sub">Per-pile for standard stocked range.</p>
        </div>
        <div class="capability-item">
          <p class="capability-label">Soil suitability</p>
          <p class="capability-value">Most profiles</p>
          <p class="capability-sub">__SOILSUB__</p>
        </div>
        <div class="capability-item">
          <p class="capability-label">Service life</p>
          <p class="capability-value">50, 75, 100+ years</p>
          <p class="capability-sub">When properly designed, installed to torque, and corrosion-rated for the soil profile.</p>
        </div>
      </div>
    </div>
  </section>

  <section class="services">
    <div class="container">
      <header class="section-head">
        <p class="eyebrow">Where it fits</p>
        <h2>__NAME__ project types</h2>
        <p class="section-sub">The same piling method, scaled to the project. Residential through to civil and government.</p>
      </header>

      <div class="usecase-grid">
        __USECASES__
      </div>
    </div>
  </section>

  <section class="capability-band" aria-label="Service area">
    <div class="container">
      <header class="section-head">
        <p class="eyebrow">Service area</p>
        <h2>__AREA_H2__</h2>
        <p class="section-sub">__AREA_SUB__</p>
      </header>
      <div class="capability-grid capability-grid-3">
        __AREAS__
      </div>
    </div>
  </section>

  <section class="process">
    <div class="container">
      <header class="section-head">
        <p class="eyebrow">How an install runs</p>
        <h2>From first call to certified install</h2>
        <p class="section-sub">A clear five-step process. Itemised quote, engineered to spec, certified on completion.</p>
      </header>

      <ol class="process-steps">
        <li class="process-step">
          <span class="process-num" aria-hidden="true">01</span>
          <h3 class="process-title">Send the details</h3>
          <p>Email plans, engineering, and a soil report to <a href="mailto:sales@totalpiling.com.au">sales@totalpiling.com.au</a>, or call Rob or Tom.</p>
        </li>
        <li class="process-step">
          <span class="process-num" aria-hidden="true">02</span>
          <h3 class="process-title">Accurate quote</h3>
          <p>Pile counts, sizes, depth, connection detail, certification - all on the page, all priced.</p>
        </li>
        <li class="process-step">
          <span class="process-num" aria-hidden="true">03</span>
          <h3 class="process-title">Engineered to spec</h3>
          <p>Pile sizing and depth confirmed against your engineer's design and the soil report. Adjustments handled before we book in, not on the day.</p>
        </li>
        <li class="process-step">
          <span class="process-num" aria-hidden="true">04</span>
          <h3 class="process-title">Installed on site</h3>
          <p>Crew arrives in __NAME__ with the right machine and pile stock for the job. Install torque is recorded on each pile.</p>
        </li>
        <li class="process-step">
          <span class="process-num" aria-hidden="true">05</span>
          <h3 class="process-title">Certified &amp; handed over</h3>
          <p>AS2159 certification and full documentation handed over. Engineered to spec, load-tested, ready to build on.</p>
        </li>
      </ol>
    </div>
  </section>

  <section class="faq">
    <div class="container">
      <header class="section-head">
        <p class="eyebrow">Common questions</p>
        <h2>Screw piling in __NAME__, answered</h2>
      </header>

      <div class="faq-list">
        __FAQS__
      </div>
    </div>
  </section>

__AREAS_MESH__

  <section class="cta-band">
    <div class="container cta-band-inner">
      <div class="cta-band-copy">
        <p class="eyebrow">Ready when you are</p>
        <h2>Quote your __NAME__ screw piling job.</h2>
        <p>Send the plans, engineering, and soil report. We'll come back with a quote, no obligation.</p>
      </div>
      <div class="cta-band-actions">
        <a href="/contact.html" class="btn btn-primary btn-lg">Request a Quote</a>
        <a href="tel:0419008549" class="btn btn-ghost btn-lg">Call Rob __PHONE_ROB__</a>
        <a href="tel:0448725807" class="btn btn-ghost btn-lg">Call Tom __PHONE_TOM__</a>
      </div>
    </div>
  </section>

</main>

__FOOTER__

<script src="../script.js" defer></script>
</body>
</html>
""".replace("__HEADER__", chrome["header"]) \
   .replace("__FOOTER__", chrome["footer"]) \
   .replace("__AREAS_MESH__", areas_block(exclude=city["slug"], with_melbourne=True)) \
   .replace("__PARAS__", paras) \
   .replace("__USECASES__", usecases) \
   .replace("__AREAS__", areas) \
   .replace("__FAQS__", faqs) \
   .replace("__GROUND_H2__", city["ground_h2"]) \
   .replace("__SOILSUB__", city["soil_sub"]) \
   .replace("__AREA_H2__", city["area_h2"]) \
   .replace("__AREA_SUB__", city["area_sub"]) \
   .replace("__EYEBROW__", city["eyebrow"]) \
   .replace("__H1__", city["h1"]) \
   .replace("__LEAD__", city["lead"]) \
   .replace("__PHOTO__", city["photo"]) \
   .replace("__PW__", str(city["photo_w"])) \
   .replace("__PH__", str(city["photo_h"])) \
   .replace("__PALT__", city["photo_alt"]) \
   .replace("__PHONE_ROB__", PHONE_ROB) \
   .replace("__PHONE_TOM__", PHONE_TOM) \
   .replace("__NAME__", city["name"])


def areas_block(exclude=None, with_melbourne=False, depth_prefix=""):
    """The mesh section, so no regional page is an orphan: the parent screw piling page
    links down to every city, and each city page links back to Melbourne and across to its
    siblings. Uses .usecase-card, a real page-body class - NOT .mega-link, which is scoped
    to .primary-nav in styles.css and renders completely unstyled outside the nav."""
    cards = []
    if with_melbourne:
        cards.append(
            '<a class="usecase-card area-link" href="/services/screw-piling.html">\n'
            '          <h3>Screw Piling Melbourne</h3>\n'
            '          <p>The main service page. Metro Melbourne and statewide coverage, '
            'residential through to government.</p>\n        </a>')
    for c in CITIES:
        if c["slug"] == exclude:
            continue
        cards.append(
            '<a class="usecase-card area-link" href="/services/screw-piling-%s.html">\n'
            '          <h3>Screw Piling %s</h3>\n          <p>%s</p>\n        </a>'
            % (c["slug"], c["name"], c["blurb"]))
    links = "\n        ".join(cards)
    return """%s
  <section class="services" aria-label="Screw piling service areas">
    <div class="container">
      <header class="section-head">
        <p class="eyebrow">Where we work</p>
        <h2>Screw piling across Victoria</h2>
        <p class="section-sub">Melbourne metro plus the regional centres. We bring the machine, the pile stock and the certification with us.</p>
      </header>
      <div class="usecase-grid">
        %s
      </div>
    </div>
  </section>
%s""" % (AREAS_START, links, AREAS_END)


def patch_parent(src):
    block = areas_block()
    if AREAS_START in src and AREAS_END in src:
        i = src.index(AREAS_START)
        j = src.index(AREAS_END) + len(AREAS_END)
        return src[:i] + block + src[j:]
    anchor = '  <section class="cta-band">'
    if anchor not in src:
        raise SystemExit("Could not find the CTA band to insert the areas block before")
    return src.replace(anchor, block + "\n" + anchor, 1)


def patch_sitemap(path):
    with open(path, encoding="utf-8") as fh:
        xml = fh.read()
    entries = []
    for c in CITIES:
        loc = "%s/services/screw-piling-%s.html" % (BASE, c["slug"])
        if loc in xml:
            continue
        entries.append(
            "  <url>\n    <loc>%s</loc>\n    <lastmod>%s</lastmod>\n"
            "    <changefreq>monthly</changefreq>\n    <priority>0.8</priority>\n  </url>"
            % (loc, TODAY))
    if not entries:
        return 0
    xml = xml.replace("</urlset>", "\n".join(entries) + "\n</urlset>")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(xml)
    return len(entries)


def main():
    with open(PARENT, encoding="utf-8") as fh:
        src = fh.read()

    chrome = {
        "ga4": slice_between(src, "  <!-- Google tag (gtag.js)", "</script>", "the GA4 tag").rstrip(),
        "fonts": slice_between(src, '  <link rel="preconnect" href="https://fonts.googleapis.com">',
                               '<link rel="stylesheet" href="../styles.css">', "the font links").rstrip(),
        "leadev": slice_between(src, "  <!-- Sutera lead events (GA4) -->", "</script>",
                                "the lead events snippet").rstrip(),
        "header": slice_between(src, '<header class="site-header"', "</header>", "the site header").rstrip(),
        "footer": slice_between(src, '<footer class="site-footer">', "</footer>", "the site footer").rstrip(),
    }

    written = []
    for city in CITIES:
        html = build_head(city, chrome) + build_body(city, chrome)
        for bad in ("—", "–"):
            if bad in html:
                raise SystemExit("Dash rule violated on the %s page" % city["name"])
        out = os.path.join(ROOT, "services", "screw-piling-%s.html" % city["slug"])
        with open(out, "w", encoding="utf-8") as fh:
            fh.write(html)
        written.append(os.path.basename(out))

    with open(PARENT, "w", encoding="utf-8") as fh:
        fh.write(patch_parent(src))

    added = patch_sitemap(os.path.join(ROOT, "sitemap.xml"))
    print("Wrote %d city pages: %s" % (len(written), ", ".join(written)))
    print("Patched services/screw-piling.html with the Areas We Service block")
    print("Sitemap: %d new entries" % added)


if __name__ == "__main__":
    main()
